practica/examen/urls.py
from django.urls import path

from . import views

app_name = "examen"

urlpatterns = [
    path('', views.index, name="index"),
    path('resolver', views.resolver, name="resolver"),
    path('registro', views.registro, name="registro")
]

practica/practica/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('examen/', include('examen.urls'))
]

practica/examen/models.py
from django.db import models

# Create your models here.
class Pregunta(models.Model):
    pregunta_texto = models.CharField(max_length=255)
    pub_date = models.DateTimeField('date_published')

    def __str__(self):
        return self.pregunta_texto

class Opcion(models.Model):
    pregunta = models.ForeignKey(Pregunta, on_delete=models.CASCADE)
    opcion_texto = models.CharField(max_length=255)
    puntos = models.IntegerField(default=0)
    
    def __str__(self):
        return self.opcion_texto

class Alumno(models.Model):
    nombre = models.CharField(max_length=200)
    email = models.EmailField()

    def __str__(self):
        return self.nombre

class Nota(models.Model):
    alumno = models.ForeignKey(Alumno, on_delete=models.CASCADE)
    nota = models.IntegerField(default=0)

    def __str__(self):
        return self.nota

practica/examen/views.py
from django.shortcuts import render

from .models import Pregunta, Opcion, Alumno, Nota
# Create your views here.

def index(request):
    lista_pregunta = Pregunta.objects.all()
    context = {
        'preguntas' : lista_pregunta
    }
    return render(request, 'index.html',context)

def resolver(request):
    preguntas = Pregunta.objects.all()
    nota = 0
    for pregunta in preguntas:
        nota = int(request.POST['pregunta_'+str(pregunta.id)])
    
    context = {
        'nota' : nota
    }

    return render(request, 'resultados.html',context)

def registro(request):
    data_nota = request.POST['nota']
    data_nombre = request.POST['nombre']
    data_email = request.POST['email']

    objAlumno = Alumno.objects.create(
        nombre = data_nombre,
        email = data_email
    )

    objNota = Nota()
    objNota.alumno = objAlumno
    objNota.nota = int(data_nota)
    objNota.save()

    context = {
        'notas' : Nota.objects.all()
    }

    return render(request,'posiciones.html',context)

practica/examen/templates/index.html
<h1>Examen de Django</h1>
<form action="{% url 'examen:resolver' %}" method="post">
    {% csrf_token %}
    <ul>
        {% for pregunta in preguntas %}
            <li>{{ pregunta.pregunta_texto }}
                <ul>
                    {% for opcion in pregunta.opcion_set.all %}
                    <li>
                        <input type="radio" name="pregunta_{{pregunta.id}}" value="{{opcion.puntos}}">
                        {{opcion.opcion_texto}}
                    </li>
                    {% endfor %}
                </ul>
            </li>
        {% endfor %}
    </ul>
    <input type="submit" value="Enviar">
</form>

practica/examen/templates/posiciones.html
<h1>TABLAS DE POSICIONES</h1>
<table border="1">
    <tr>
        <th>Alumno</th>
        <th>Nota</th>
    </tr>
    {% for nota in notas %}
    <tr>
        <td>
            {{nota.alumno.nombre}}
        </td>
        <td>
            {{nota.nota}}
        </td>
    </tr>
    {% endfor %}
</table>
<a href="{% url 'examen:index' %}">Volver a la pagina principal</a>

practica/examen/templates/resultados.html
<h1>Resultados</h1>
<p>Tu nota es {{nota}}</p>

<form action="{% url 'examen:registro' %}" method="post">
    {% csrf_token %}
    <input type="hidden" name="nota" value="{{nota}}">
    Registre dato de usuario<br>
    Nombre : <input type="text" name="nombre"><br>
    Email : <input type="text" name="email"><br>
    <input type="submit" value="REGISTRAR NOTA DE USUARIO">
</form>